# .travis.yml

language: python
sudo: true

env:
  - LUA="lua=5.1"
  - LUA="lua=5.2"
  - LUA="lua=5.3"
  - LUA="luajit=2.0"
  - LUA="luajit=2.1"

before_install:
  - pip install hererocks
  - hererocks lua_install -r^ --$LUA
  - export PATH=$PATH:$PWD/lua_install/bin
  - # --- installs development dependencies ---
    # --- designed for debian linux systems ---
  - set -e
  - export CFLAGS="-Wno-error"
  - # install cmake and git
  - sudo apt-get install -y cmake git-core
  - # install lua
  - sudo apt-get install -y lua5.1 liblua5.1-0-dev luarocks
  - # install json-c
  - sudo apt-get install -y dh-autoreconf
  - git clone https://github.com/json-c/json-c.git --depth=1 && cd json-c
  - sh autogen.sh && ./configure && sudo make && sudo make install && cd ..
  - # install openwrt libubox and uci
  - git clone https://git.openwrt.org/project/libubox.git --depth=1 && cd libubox
  - sudo cmake . && sudo make install && cd ..
  - git clone https://git.openwrt.org/project/uci.git --depth=1 && cd uci
  - sudo cmake . && sudo make install && cd ..
  - # update links to shared libraries
  - sudo ldconfig -v
  - # install luafilesystem
  - sudo luarocks install luafilesystem
  - # install luaunit
  - git clone https://github.com/bluebird75/luaunit.git --depth=1
  - mkdir -p /usr/share/lua/5.1/
  - cd luaunit && sudo cp luaunit.lua /usr/share/lua/5.1/ && cd ..
  - test -f /usr/share/lua/5.1/luaunit.lua
  - # clean
  - sudo rm -rf json-c libubox uci luaunit

install:
  - sudo luarocks install luacheck
  
script:
   - ./runtests
